using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TodoApp.Api.Data.Migrations
{
    /// <inheritdoc />
    public partial class ChangeIdToInt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // PostgreSQLはuuid→integerの直接キャストができないため、マイグレーションをraw SQLで書き直します。
            migrationBuilder.Sql("ALTER TABLE todos DROP CONSTRAINT IF EXISTS \"PK_todos\";");
            migrationBuilder.Sql("ALTER TABLE todos DROP COLUMN id;");
            migrationBuilder.Sql("ALTER TABLE todos ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE todos DROP CONSTRAINT IF EXISTS \"PK_todos\";");
            migrationBuilder.Sql("ALTER TABLE todos DROP COLUMN id;");
            migrationBuilder.Sql("ALTER TABLE todos ADD COLUMN id uuid DEFAULT gen_random_uuid() PRIMARY KEY;");
        }
    }
}
